import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import EventList from '../components/events/event-list'
import { getFeaturedEvents } from '../service/api-util'

export default function HomePage(props) {

  console.log(props);


  return (
    <div className={styles.container}>
      <Head>
        <title>Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div>
        <EventList items={props.events} />
      </div>
    </div>
  )
}

export async function getStaticProps() {
  const featuredEvents = await getFeaturedEvents()
  return {
    props: {
      events: featuredEvents
    },
    //auto-refresh for half-day  43200sec
     revalidate: 43200
  }
}
